const randIngs = {saladIngredients:
{base: [
    "Kale",
    "Rucola",
    "Iceberg Lettuce",
    "Lettuce",
    "Spinach",
    "Red Leaf Lettuce",
    "Romaine Lettuce",
    "Cabbage",
    "Red Cabbage"],
toppings: [
    "Broccoli",
    "Cauliflower",
    "Chinese Cabbage",
    "Chinese Broccoli",
    "Green Pepper",
    "Red Pepper",
    "Yellow Pepper",
    "Orange Pepper",
    "Tomato",
    "Yellow Tomatoes",
    "Black Tomato",
    "Cherry Tomato",
    "Avocado",
    "Carrots",
    "Celery",
    "Onions",
    "Red Onions",
    "Chives",
    "Mushrooms",
    "Corn",
    "Olives",
    "Beets",
    "Zucchini",
    "Beans",
    "Black Beans",
    "Red Beans",
    "Kidney Beans",
    "Black Eyed Beans",
    "Capers",
    "Green Beans",
    "Lentils",
    "Parsley",
    "Dill",
    "Grilled Eggplant",
    "Sundried Tomatoes",
    "Cucumber",
    "Pickles",
    "Orange",
    "Strawberries",
    "Fig",
    "Grapes",
    "Raisins",
    "Apples",
    "Cranberries",
    "Goji Berry",
    "Ham",
    "Bacon",
    "Turkey",
    "Grilled Chicken",
    "Chicken Nuggets",
    "Tuna",
    "Smoked Salmon",
    "Hard Boiled Eggs",
    "Shrimp",
    "Octopus",
    "Quinoa",
    "Sesame Seeds",
    "Pumpkin Seed",
    "Walnuts",
    "Almonds",
    "Pinoli (Pine Nuts)",
    "Croutons",
    "Rusk",
    "Pasta",
    "Bulgur",
    "Couscous",
    "Oregano",
    "Basil",
    "Tabasco",
    "Honey",
    "Peanut Butter",
    "Yogurt",
    "Parmesan",
    "Goat Cheese",
    "Blue Cheese",
    "Feta Cheese",
    "Spray Cheese/Cheese in a Can",
    "Grated Cheese",
    "Cottage Cheese"],
finish: [
    "Balsamic Vinegar",
    "Apple Cider Vinegar",
    "Vinegar",
    "Mustard",
    "Honey Mustard Dressing",
    "Caesar Dressing",
    "Blue Cheese Dressing",
    "Extra Virgin Olive Oil",
    "Lemon",
    "Sauce Vierge",
    "Mayonaise",
    "Tahini"
]},
sandwichIngredients: {
  base: [
    "White Bread",
    "Sourdough",
    "Rye Bread",
    "Hot Dog Bun",
    "Flour Tortilla",
    "Challah Bread",
    "Croissant",
    "Wheat Bread",
    "Multigrain Bread",
    "Foccacia",
    "Bagel",
    "Naan",
    "Baguette",
    "Ciabatta",
    "Pita"
  ],
  toppings: [
    "Aloo Tikki",
    "Antipasto",
    "Apple Butter",
    "Artichoke Hearts",
    "Baked Beans",
    "Black Bean Burger",
    "Cabbage",
    "Carrots",
    "Cashew Cheese",
    "Celery",
    "Chickpea Salad Sandwich",
    "Chips",
    "Chow-Chow",
    "Cinnamon",
    "Coriander Chutney",
    "Cress",
    "Cucumber",
    "Dark Chocolate",
    "Falafel",
    "Fried Mushrooms",
    "Fried Potatoes",
    "Garlic",
    "Green Peppers",
    "Green Tomato Chutney",
    "Grilled Eggplant",
    "Grilled Mushrooms",
    "Hash Browns",
    "Heirloom Tomatoes",
    "Herbs",
    "Lettuce",
    "Mesclun",
    "Mushrooms",
    "Fried Onion",
    "Pea Shoot",
    "Peach Butter",
    "Peach Preserves",
    "Peanut Butter",
    "Pickled Beets",
    "Poblano",
    "Portobello",
    "Pumpkin Butter",
    "Raisins",
    "Red Capsicum Dip",
    "Red Onions",
    "Sauerkraut",
    "Scrambled Tofu",
    "Sesame Seeds",
    "Spaghetti",
    "Spinach",
    "Sunflower Seed Butter",
    "Tofu",
    "Tomatillo Guacamole",
    "Tomato",
    "Veggie Burger",
    "Vidalia Onion (Georgia)",
    "Watercress",
    "Turkey",
    "Ham",
    "Salami",
    "Prosciutto",
    "Pepperoni",
    "Swiss Cheese",
    "American Cheese",
    "Gruyere",
    "Provalone",
    "Blue Cheese",
    "Gorgonzola",
    "Arugala",
    "Mortadella",
    "Pastrami",
    "Bacon"
  ],
  finish: [
    "Blackberry Jelly",
    "Blueberry Jam",
    "Chili Sauce",
    "Chimichurri",
    "Grape Jelly",
    "Habanero Salsa",
    "Hot Sauce",
    "Hummus",
    "Mustard",
    "Pesto",
    "Muhammara",
    "Pico De Gallo",
    "Plum Jam",
    "Roasted Tomato Salsa",
    "Strawberry Jam",
    "Sweet Chili Sauce",
    "Tahini",
    "Tamarind Sauce",
    "Tapenade",
    "Tomato Sauce",
    "Sesame Oil",
    "Vinaigrette",
  ]},
  soupIngredients: {
    base: [
      "Chicken Broth",
      "Vegetable Broth",
      "Beef Broth",
    ],
    toppings: [
      "Amaranth",
      "Artichoke",
      "Asparagus",
      "Bamboo Shoot",
      "Beet Greens",
      "Bok Choy",
      "Broccoli",
      "Brussels Sprout",
      "Cabbage",
      "Carrot",
      "Catsear",
      "Cauliflower",
      "Celery",
      "Celtuce",
      "Chaya",
      "Chickpeas",
      "Chives",
      "Cress",
      "Cucumber",
      "Dill",
      "Elephant Garlic",
      "Endive",
      "Fat Hen",
      "Fiddlehead",
      "Fluted Pumpkin",
      "Garlic",
      "Garlic Chives",
      "Ginger",
      "Grain Amaranth",
      "Green Garlic",
      "Green Peppers",
      "Guarana",
      "Kale",
      "Leek",
      "Lettuce",
      "Mint",
      "Mustard Greens",
      "Onion",
      "Peanuts",
      "Peas",
      "Potatoes",
      "Pumpkin",
      "Purple Asparagus",
      "Purple Endive",
      "Purple Pepper",
      "Radish",
      "Red Pepper",
      "Rocket",
      "Sweet Potato",
      "Taro",
      "Tree Onion",
      "Turnip",
      "Turnip Green",
      "Wasabi",
      "White Asparagus",
      "White Radish",
      "Wild Arugula",
      "Yellow Chives",
      "Yellow Pepper",
      "Plantain",
      "Eggplant",
      "Ground Beef",
      "Shredded Chicken",
      "Soft-Boiled Egg",
      "Pork Slices",
      "Ramen Noodles",
      "Penne Pasta",
      "Macaroni",
      "Jasmine Rice",
      "Brown Rice",
      "Nori",
      "Chicken Thighs",
      "Udon Noodles",
      "Mussels",
      "Prawns",
    ],
    finish: [
      "Coriander",
      "Black Pepper",
      "Parmesan Cheese",
      "Fried Onions",
      "Sesame Oil",
      "Chili Oil",
      "Rice Vingar",
      "Croutons",
      "Oyster Crackers",
      "Torilla Chips",
    ]
  }
}

export default randIngs;
